"""Prepare a FULL-TEXT review of every doubtful label, to run after each corpus change.

Why. On 2026-09-27 two "unanswerable" labels turned out wrong (EXPERIMENT_LOG.md 6p):
n16 had been graded from a ~290-character passage preview that stopped just before the
storage text, and q19 from a low top-1 score while the relevant passage sat at rank 2.
A preview is not the passage, and a low score is not proof of absence.

What it does. Collects every query that is either marked unanswerable or only marginal,
using the wording the deployed system actually sends (``generated_query`` for disease
cases, the authored query otherwise), and writes them to a candidate file that
``check_coverage.py`` can score. That script then dumps the FULL text of every retrieved
passage to a markdown file, which is what gets read before any label is kept or changed.

Run it after Vishvavallabha is ingested — new passages may answer queries that nothing
answered before.

Usage:
    python scripts/review_labels.py
    python scripts/check_coverage.py data/eval/_label_review_queries.json labelreview
    -> read results/coverage_passages_labelreview.md (full passages, not previews)
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SILVER = ROOT / "data" / "eval" / "silver_queries.json"
OUT = ROOT / "data" / "eval" / "_label_review_queries.json"


def main() -> int:
    qs = json.loads(SILVER.read_text(encoding="utf-8"))["queries"]
    picked = []
    for q in qs:
        doubtful = (not q.get("expect_answerable")) or q.get("coverage_tier") == "marginal"
        if not doubtful:
            continue
        picked.append({
            "id": q["id"],
            "disease": q.get("disease"),
            "domain": q.get("domain"),
            # the wording the deployed system sends; no expect_answerable key, so
            # check_coverage.py scores every one of them
            "query": q.get("generated_query") or q["query"],
            "current_label": ("answerable" if q.get("expect_answerable") else
                              q.get("unanswerable_kind", "unanswerable")),
            "current_tier": q.get("coverage_tier"),
        })
    OUT.write_text(json.dumps({
        "_about": "Doubtful labels for full-text review; generated by review_labels.py. "
                  "Not an evaluation set - do not load it as one.",
        "queries": picked,
    }, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"{len(picked)} doubtful labels -> {OUT.relative_to(ROOT)}")
    for p in picked:
        print(f"  {p['id']:5} {p['current_label']:13} {p['query'][:60]}")
    print("\nNext:")
    print(f"  python scripts/check_coverage.py {OUT.relative_to(ROOT)} labelreview")
    print("  then read results/coverage_passages_labelreview.md in full")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
