"""Phase 6 multi-task training utilities for the soil module.

Mirrors the structure of :mod:`src.disease.train` (CheckpointManager,
auto_batch_size, train/eval helpers) but adapts each to the joint
multi-task setting where:

- Each batch contains samples from three source datasets
- Each sample supervises exactly one of three task heads
- The other two heads receive ``-1`` (ignored by cross-entropy)

The training loop and notebook live in
``notebooks/phase6_soil_training.ipynb`` (generated by
``scripts/build_phase6_notebook.py``). This module exposes the
building blocks; the notebook composes them.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any

from src.utils.logging_setup import get_logger

if TYPE_CHECKING:
    import torch
    from torch.utils.data import DataLoader

_LOGGER = get_logger(__name__)


# Per-head loss weights. Uniform by default — every head contributes
# equally to the total. Tune later only if one head dominates training.
TASK_WEIGHTS: dict[str, float] = {
    "soil_type": 1.0,
    "moisture": 1.0,
    "texture": 1.0,
}

# Locked model repo for the Phase 6 multi-task checkpoint trail.
DEFAULT_MODEL_REPO: str = "ankit-iiitdmj/iks-soil-multitask"


# --------------------------------------------------------------------- #
# Auto batch size
# --------------------------------------------------------------------- #


def auto_batch_size(
    img_size: int = 224, model_name: str = "efficientnet_b0",
) -> int:
    """Pick a Colab-safe batch size for B0 @ 224x224 + mixed precision.

    Bucketed by GPU VRAM:

    - >=14 GiB (T4 free tier, L4, A100): 64
    - >=10 GiB: 32
    - else: 16

    Falls back to 16 on CPU / no GPU detected — the notebook is meant
    for Colab T4 so the CPU path is a smoke-test safety only.
    """
    try:
        import torch  # noqa: PLC0415
    except ImportError:
        chosen = 16
        print(f"Auto batch size for {model_name} at {img_size}x{img_size}: {chosen} (no torch)")
        return chosen

    if not torch.cuda.is_available():
        chosen = 16
        print(f"Auto batch size for {model_name} at {img_size}x{img_size}: {chosen} (no CUDA)")
        return chosen

    total_gib = torch.cuda.get_device_properties(0).total_memory / (1024**3)
    if total_gib >= 14:
        chosen = 64
    elif total_gib >= 10:
        chosen = 32
    else:
        chosen = 16
    print(f"Auto batch size for {model_name} at {img_size}x{img_size}: {chosen}")
    return chosen


# --------------------------------------------------------------------- #
# Multi-task loss
# --------------------------------------------------------------------- #


def compute_multitask_loss(
    predictions: dict[str, "torch.Tensor"],
    batch: dict[str, Any],
) -> tuple["torch.Tensor", dict[str, float]]:
    """Weighted sum of per-head cross-entropy with ``ignore_index=-1``.

    Parameters
    ----------
    predictions
        Dict ``{"soil_type": (B, 7), "moisture": (B, 3), "texture": (B, 3)}``
        — the output of :meth:`SoilMultiTaskClassifier.forward`.
    batch
        Dict with at least the keys ``"soil_type_label"``,
        ``"moisture_label"``, ``"texture_label"``, each a length-B
        ``LongTensor``. Samples that don't supervise a given head
        carry ``-1`` for that label.

    Returns
    -------
    (total_loss, per_head_losses)
        ``total_loss`` is a scalar ``Tensor`` ready for ``.backward()``.
        ``per_head_losses`` maps head name -> Python float (detached) for
        logging.

    Notes
    -----
    Cross-entropy with ``ignore_index=-1`` returns NaN when **all**
    samples in the batch carry ``-1`` for that head — there are zero
    elements to average over. We guard against that case and substitute
    a zero with the right device + dtype + requires_grad, so the
    backward pass produces zero gradient on that head without
    contaminating the loss with NaN.
    """
    import torch  # noqa: PLC0415
    from torch.nn import functional as F  # noqa: PLC0415

    per_head_losses: dict[str, float] = {}
    head_loss_tensors: list[torch.Tensor] = []

    head_to_label_key: dict[str, str] = {
        "soil_type": "soil_type_label",
        "moisture": "moisture_label",
        "texture": "texture_label",
    }

    for head, weight in TASK_WEIGHTS.items():
        logits = predictions[head]
        labels = batch[head_to_label_key[head]]
        # If labels isn't a LongTensor already, coerce — DataLoader
        # collate may have left it as an int tensor of a different dtype.
        if labels.dtype != torch.long:
            labels = labels.long()
        loss = F.cross_entropy(
            logits, labels, ignore_index=-1, reduction="mean",
        )
        if torch.isnan(loss):
            # No valid (non-ignored) samples in this batch for this head.
            # Substitute zero in the SAME computation graph so gradient
            # propagates as 0 (rather than NaN poisoning .backward()).
            loss = (logits.sum() * 0.0)
        head_loss_tensors.append(weight * loss)
        per_head_losses[head] = float(loss.detach().item())

    total_loss = torch.stack(head_loss_tensors).sum()
    return total_loss, per_head_losses


# --------------------------------------------------------------------- #
# Training / evaluation loops
# --------------------------------------------------------------------- #


@dataclass
class _EpochLossAccum:
    """Running per-task + total loss accumulator for one epoch."""

    n_batches: int = 0
    sum_total: float = 0.0
    sum_per_head: dict[str, float] = None  # type: ignore[assignment]

    def __post_init__(self) -> None:
        if self.sum_per_head is None:
            self.sum_per_head = {head: 0.0 for head in TASK_WEIGHTS}

    def update(self, total: float, per_head: dict[str, float]) -> None:
        self.n_batches += 1
        self.sum_total += float(total)
        for head, val in per_head.items():
            self.sum_per_head[head] = self.sum_per_head.get(head, 0.0) + float(val)

    def averages(self) -> dict[str, float]:
        n = max(1, self.n_batches)
        out = {f"loss_{head}": self.sum_per_head[head] / n for head in TASK_WEIGHTS}
        out["loss_total"] = self.sum_total / n
        return out


def train_one_epoch(
    model: Any,
    loader: "DataLoader",
    optimizer: Any,
    scaler: Any,
    device: str,
) -> dict[str, float]:
    """Run one training epoch over the combined-loader batches.

    Returns the per-head average losses plus the total, as Python floats:
    ``{"loss_soil_type", "loss_moisture", "loss_texture", "loss_total"}``.
    """
    import torch  # noqa: PLC0415

    model.train()
    accum = _EpochLossAccum()
    use_cuda = device.startswith("cuda")

    for batch in loader:
        images = batch["image"].to(device, non_blocking=True)
        prepared_batch = {
            "soil_type_label": batch["soil_type_label"].to(device, non_blocking=True),
            "moisture_label": batch["moisture_label"].to(device, non_blocking=True),
            "texture_label": batch["texture_label"].to(device, non_blocking=True),
        }
        optimizer.zero_grad(set_to_none=True)

        if use_cuda:
            with torch.amp.autocast("cuda"):
                predictions = model(images)
                total_loss, per_head_losses = compute_multitask_loss(
                    predictions, prepared_batch,
                )
            scaler.scale(total_loss).backward()
            scaler.step(optimizer)
            scaler.update()
        else:
            predictions = model(images)
            total_loss, per_head_losses = compute_multitask_loss(
                predictions, prepared_batch,
            )
            total_loss.backward()
            optimizer.step()

        accum.update(float(total_loss.detach().item()), per_head_losses)

    return accum.averages()


def evaluate_per_task(
    model: Any,
    val_loaders: dict[str, "DataLoader"],
    device: str,
) -> dict[str, dict[str, float]]:
    """Per-task top-1 and macro F1 on dedicated single-task val loaders.

    Parameters
    ----------
    model
        :class:`SoilMultiTaskClassifier` instance.
    val_loaders
        Dict mapping head name (``"soil_type"`` / ``"moisture"`` /
        ``"texture"``) to a ``DataLoader`` whose batches are
        ``(images, labels)`` for ONLY that head's data. The labels are
        plain ``LongTensor`` (no ``-1``).
    device
        ``"cuda"`` or ``"cpu"``.

    Returns
    -------
    dict
        ``{head: {"top1_accuracy": float, "macro_f1": float, "n_samples": int}}``.
    """
    import torch  # noqa: PLC0415
    from sklearn.metrics import f1_score  # noqa: PLC0415

    model.eval()
    results: dict[str, dict[str, float]] = {}
    for head, loader in val_loaders.items():
        y_true: list[int] = []
        y_pred: list[int] = []
        with torch.no_grad():
            for batch in loader:
                if isinstance(batch, dict):
                    images = batch["image"]
                    labels = batch[f"{head}_label"]
                else:
                    images, labels = batch
                images = images.to(device, non_blocking=True)
                labels = labels.to(device, non_blocking=True)
                logits_dict = model(images)
                preds = logits_dict[head].argmax(dim=1)
                y_true.extend(int(v) for v in labels.tolist())
                y_pred.extend(int(v) for v in preds.tolist())
        n = len(y_true)
        if n == 0:
            results[head] = {"top1_accuracy": 0.0, "macro_f1": 0.0, "n_samples": 0}
            continue
        correct = sum(1 for t, p in zip(y_true, y_pred, strict=True) if t == p)
        top1 = correct / n
        macro = float(
            f1_score(y_true, y_pred, average="macro", zero_division=0.0)
        )
        results[head] = {
            "top1_accuracy": top1, "macro_f1": macro, "n_samples": n,
        }
    return results


# --------------------------------------------------------------------- #
# Checkpoint manager (HF Hub backed)
# --------------------------------------------------------------------- #


class SoilCheckpointManager:
    """Save/load multi-task soil checkpoints to/from the HF Hub model repo.

    Matches the contract of :class:`src.disease.train.CheckpointManager`
    so the Phase 6 notebook reads naturally to anyone who saw Phase 5.

    All HF Hub interactions are lazy — instantiation does NOT touch the
    network. The repo is created (private) on the first call to
    :meth:`save`, mirroring the no-side-effects-on-import contract from
    Phase 5.
    """

    def __init__(
        self,
        repo_id: str = DEFAULT_MODEL_REPO,
        work_dir: Path | None = None,
    ) -> None:
        self.repo_id = repo_id
        self.work_dir = (
            Path(work_dir) if work_dir is not None else Path(".") / "_checkpoints" / "soil"
        )
        self.work_dir.mkdir(parents=True, exist_ok=True)

    def _api(self):
        from huggingface_hub import HfApi  # noqa: PLC0415

        return HfApi()

    def _ensure_repo(self) -> None:
        self._api().create_repo(
            repo_id=self.repo_id,
            repo_type="model",
            private=True,
            exist_ok=True,
        )

    def try_load_latest(self) -> dict[str, Any] | None:
        """Pull ``checkpoint_latest.pt`` from HF Hub. ``None`` on 404."""
        from huggingface_hub import hf_hub_download  # noqa: PLC0415
        from huggingface_hub.errors import (  # noqa: PLC0415
            EntryNotFoundError,
            RepositoryNotFoundError,
        )
        import torch  # noqa: PLC0415

        try:
            local_path = hf_hub_download(
                repo_id=self.repo_id,
                filename="checkpoint_latest.pt",
                repo_type="model",
                cache_dir=str(self.work_dir / ".hf_cache"),
            )
        except (RepositoryNotFoundError, EntryNotFoundError):
            return None
        except Exception as exc:  # noqa: BLE001
            _LOGGER.warning("HF Hub load failed: %s", exc)
            return None
        return torch.load(local_path, map_location="cpu", weights_only=False)

    def save(
        self,
        *,
        epoch: int,
        model_state: dict[str, Any],
        optimizer_state: dict[str, Any] | None,
        scheduler_state: dict[str, Any] | None,
        scaler_state: dict[str, Any] | None,
        history: list[dict[str, Any]],
        val_metrics: dict[str, Any],
    ) -> Path:
        """Push ``checkpoint_latest.pt`` and ``history.json`` to HF Hub."""
        import torch  # noqa: PLC0415

        self._ensure_repo()
        local_path = self.work_dir / "checkpoint_latest.pt"
        torch.save(
            {
                "epoch": int(epoch),
                "model_state": model_state,
                "optimizer_state": optimizer_state,
                "scheduler_state": scheduler_state,
                "scaler_state": scaler_state,
                "history": list(history),
                "val_metrics": dict(val_metrics),
            },
            local_path,
        )
        self._upload(local_path, "checkpoint_latest.pt")

        history_path = self.work_dir / "history.json"
        with history_path.open("w", encoding="utf-8") as fh:
            json.dump(history, fh, indent=2)
        self._upload(history_path, "history.json")
        return local_path

    def save_best(
        self,
        *,
        epoch: int,
        model_state: dict[str, Any],
        val_metrics: dict[str, Any],
    ) -> Path:
        """Push ``checkpoint_best.pt`` separately."""
        import torch  # noqa: PLC0415

        self._ensure_repo()
        best_path = self.work_dir / "checkpoint_best.pt"
        torch.save(
            {
                "epoch": int(epoch),
                "model_state": model_state,
                "val_metrics": dict(val_metrics),
            },
            best_path,
        )
        self._upload(best_path, "checkpoint_best.pt")
        return best_path

    def _upload(self, local_path: Path, repo_path: str) -> None:
        self._api().upload_file(
            path_or_fileobj=str(local_path),
            path_in_repo=repo_path,
            repo_id=self.repo_id,
            repo_type="model",
        )
        _LOGGER.info(
            "Pushed %s -> %s/%s", local_path.name, self.repo_id, repo_path,
        )


__all__ = [
    "DEFAULT_MODEL_REPO",
    "SoilCheckpointManager",
    "TASK_WEIGHTS",
    "auto_batch_size",
    "compute_multitask_loss",
    "evaluate_per_task",
    "train_one_epoch",
]
